longhorn:
  csi:
    kubeletRootDir: "/var/lib/kubelet"
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1
    snapshotterReplicaCount: 1
  persistence:
    defaultClassReplicaCount: 1
  preUpgradeChecker:
    jobEnabled: false
  ingress:
    enabled: true
    host: ""
    annotations: 
      "cert-manager.io/cluster-issuer": "letsencrypt"
      "nginx.ingress.kubernetes.io/auth-type": "basic"
      "nginx.ingress.kubernetes.io/auth-secret": "htpasswd"
      "nginx.ingress.kubernetes.io/auth-realm": "Protected Area"

htpasswdVaultPath: ""
